// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package injector

import (
	"github.com/linzhengen/ddd-gin-admin/application"
	"github.com/linzhengen/ddd-gin-admin/domain/repository"
	"github.com/linzhengen/ddd-gin-admin/interfaces/action"
)

// Injectors from wire.go:

// BuildInjector build injector use wire.
func BuildInjector() action.Action {
	helloWorldRepository := repository.NewHelloWorldRepository()
	helloWorldApp := application.NewHelloWorldApp(helloWorldRepository)
	helloWorldAction := action.NewHelloWorldAction(helloWorldApp)
	actionAction := action.NewAction(helloWorldAction)
	return actionAction
}
